import json
from io import StringIO
from pathlib import Path

from rich.console import Console

from themectl.hooks import (
    _update_editor_settings,
    _update_neovim_theme_file,
    _update_tmux_config,
)
from themectl.themes import Theme


def _console() -> Console:
    return Console(file=StringIO(), record=True)


def test_update_editor_settings_handles_comments(tmp_path: Path) -> None:
    settings = tmp_path / "settings.json"
    settings.write_text('// comment\n{"someKey": true}')

    changed = _update_editor_settings([settings], "Tokyo Night", _console(), "VSCode")

    assert changed is True
    data = json.loads(settings.read_text())
    assert data["workbench.colorTheme"] == "Tokyo Night"


def test_update_neovim_theme_file_rewrites_colorscheme(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    theme_file = home / ".config" / "nvim" / "lua" / "plugins" / "theme.lua"
    theme_file.parent.mkdir(parents=True)
    theme_file.write_text('return {\n  colorscheme = "tokyonight"\n}\n')

    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("THEMECTL_HOME", str(home))

    _update_neovim_theme_file("catppuccin", _console())

    assert 'colorscheme = "catppuccin"' in theme_file.read_text()


def test_update_tmux_config_generates_file(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("THEMECTL_HOME", str(home))

    theme = Theme(
        name="Test",
        slug="test",
        display_name="Test",
        wallpapers=[],
        raw={
            "tmux": {
                "statusBackground": "#000000",
                "statusForeground": "#ffffff",
                "windowStatusCurrent": "#ff00ff",
                "paneActiveBorder": "#00ff00",
                "paneInactiveBorder": "#222222",
            }
        },
    )

    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: None)

    _update_tmux_config(theme, _console())

    conf = home / ".tmux.conf.local"
    assert conf.exists()
    contents = conf.read_text()
    assert "# Generated by themectl" in contents
    assert "#ff00ff" in contents
