import json
from io import StringIO
from pathlib import Path

from rich.console import Console

from themectl.hooks import (
    _update_editor_settings,
    _update_neovim_theme_file,
    _update_tmux_config,
    reload_alacritty,
    reload_hyprland,
    update_wallpaper,
)
from themectl.themes import Theme


def _console() -> Console:
    return Console(file=StringIO(), record=True)


def test_update_editor_settings_handles_comments(tmp_path: Path) -> None:
    settings = tmp_path / "settings.json"
    settings.write_text('// comment\n{"someKey": true}')

    changed = _update_editor_settings([settings], "Tokyo Night", _console(), "VSCode")

    assert changed is True
    data = json.loads(settings.read_text())
    assert data["workbench.colorTheme"] == "Tokyo Night"


def test_update_neovim_theme_file_rewrites_colorscheme(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    theme_file = home / ".config" / "nvim" / "lua" / "plugins" / "theme.lua"
    theme_file.parent.mkdir(parents=True)
    theme_file.write_text('return {\n  colorscheme = "tokyonight"\n}\n')

    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("THEMECTL_HOME", str(home))

    _update_neovim_theme_file("catppuccin", _console())

    assert 'colorscheme = "catppuccin"' in theme_file.read_text()


def test_update_tmux_config_generates_file(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("THEMECTL_HOME", str(home))

    theme = Theme(
        name="Test",
        slug="test",
        display_name="Test",
        wallpapers=[],
        raw={
            "tmux": {
                "statusBackground": "#000000",
                "statusForeground": "#ffffff",
                "windowStatusCurrent": "#ff00ff",
                "paneActiveBorder": "#00ff00",
                "paneInactiveBorder": "#222222",
            }
        },
    )

    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: None)

    _update_tmux_config(theme, _console())

    conf = home / ".tmux.conf.local"
    assert conf.exists()
    contents = conf.read_text()
    assert "# Generated by themectl" in contents
    assert "#ff00ff" in contents


def test_reload_alacritty_uses_msg(monkeypatch) -> None:
    def fake_which(name: str) -> str | None:
        if name == "alacritty":
            return "/usr/bin/alacritty"
        return None

    monkeypatch.setattr("themectl.hooks.shutil.which", fake_which)

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    reload_alacritty(console)

    assert calls == [["/usr/bin/alacritty", "msg", "config", "reload"]]
    assert "Reloaded Alacritty config" in console.export_text()


def test_reload_alacritty_falls_back_to_signal(monkeypatch) -> None:
    def fake_which(name: str) -> str | None:
        if name == "alacritty":
            return "/usr/bin/alacritty"
        if name in {"pkill", "killall"}:
            return "/usr/bin/pkill"
        return None

    monkeypatch.setattr("themectl.hooks.shutil.which", fake_which)

    calls: list[list[str]] = []

    class MsgFail:
        returncode = 1
        stderr = "boom"

    class Ok:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        if cmd[0] == "/usr/bin/alacritty":
            return MsgFail()
        return Ok()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    reload_alacritty(console)

    assert calls[0] == ["/usr/bin/alacritty", "msg", "config", "reload"]
    assert calls[1][0] == "/usr/bin/pkill"
    assert calls[2][0] == "/usr/bin/pkill"
    assert "SIGUSR1" in console.export_text()


def test_reload_hyprland_discovers_signature(tmp_path: Path, monkeypatch) -> None:
    runtime = tmp_path / "runtime"
    instance = runtime / "hypr" / "sig123"
    instance.mkdir(parents=True)

    monkeypatch.setenv("XDG_RUNTIME_DIR", str(runtime))
    monkeypatch.setenv("HYPRLAND_INSTANCE_SIGNATURE", "")
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Linux")
    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: "/usr/bin/hyprctl")

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    reload_hyprland(console)

    assert calls, "hyprctl should be invoked when signature is discovered"
    assert "-i" in calls[0]
    assert "sig123" in calls[0]
    assert "Reloaded Hyprland" in console.export_text()


def test_reload_hyprland_skips_when_unavailable(monkeypatch) -> None:
    monkeypatch.delenv("HYPRLAND_INSTANCE_SIGNATURE", raising=False)
    monkeypatch.delenv("XDG_RUNTIME_DIR", raising=False)
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Linux")
    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: "/usr/bin/hyprctl")

    console = _console()
    reload_hyprland(console)

    output = console.export_text()
    assert "signature unavailable" in output


def test_update_wallpaper_runs_swww(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    background = home / ".config" / "omarchy" / "current" / "background"
    background.parent.mkdir(parents=True)
    background.write_text("fake-image")

    monkeypatch.setenv("THEMECTL_HOME", str(home))
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Linux")
    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: "/usr/bin/swww")

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    update_wallpaper(console)

    assert calls, "swww should be invoked"
    assert str(background) in calls[0]
    assert "Updated wallpaper" in console.export_text()
