import json
from io import StringIO
from pathlib import Path

from rich.console import Console

from themectl.hooks import (
    _update_editor_settings,
    _update_neovim_theme_file,
    _update_tmux_config,
    reload_alacritty,
    reload_hyprland,
    update_wallpaper,
)
from themectl.themes import Theme


def _console() -> Console:
    return Console(file=StringIO(), record=True)


def test_update_editor_settings_handles_comments(tmp_path: Path) -> None:
    settings = tmp_path / "settings.json"
    settings.write_text('// comment\n{"someKey": true}')

    changed = _update_editor_settings([settings], "Tokyo Night", _console(), "VSCode")

    assert changed is True
    data = json.loads(settings.read_text())
    assert data["workbench.colorTheme"] == "Tokyo Night"


def test_update_neovim_theme_file_rewrites_colorscheme(
    tmp_path: Path, monkeypatch
) -> None:
    home = tmp_path / "home"
    theme_file = home / ".config" / "nvim" / "lua" / "plugins" / "theme.lua"
    theme_file.parent.mkdir(parents=True)
    theme_file.write_text('return {\n  colorscheme = "tokyonight"\n}\n')

    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("THEMECTL_HOME", str(home))

    _update_neovim_theme_file("catppuccin", _console())

    assert 'colorscheme = "catppuccin"' in theme_file.read_text()


def test_update_tmux_config_generates_file(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("THEMECTL_HOME", str(home))

    theme = Theme(
        name="Test",
        slug="test",
        display_name="Test",
        wallpapers=[],
        raw={
            "tmux": {
                "statusBackground": "#000000",
                "statusForeground": "#ffffff",
                "windowStatusCurrent": "#ff00ff",
                "paneActiveBorder": "#00ff00",
                "paneInactiveBorder": "#222222",
            }
        },
    )

    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: None)

    _update_tmux_config(theme, _console())

    conf = home / ".tmux.conf.local"
    assert conf.exists()
    contents = conf.read_text()
    assert "# Generated by themectl" in contents
    assert "#ff00ff" in contents


def test_reload_alacritty_touches_config(tmp_path: Path, monkeypatch) -> None:
    config_dir = tmp_path / ".config" / "alacritty"
    config_dir.mkdir(parents=True)
    config = config_dir / "alacritty.toml"
    config.write_text("# test config")

    monkeypatch.setattr("themectl.hooks.get_home", lambda: tmp_path)

    def fake_which(name: str) -> str | None:
        if name in ("sudo", "touch"):
            return f"/usr/bin/{name}"
        return None

    monkeypatch.setattr("themectl.hooks.shutil.which", fake_which)

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    reload_alacritty(console)

    assert calls == [["/usr/bin/sudo", "/usr/bin/touch", str(config)]]
    assert "Reloaded Alacritty config" in console.export_text()


def test_reload_alacritty_skips_when_no_config(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr("themectl.hooks.get_home", lambda: tmp_path)

    console = _console()
    reload_alacritty(console)

    assert "skipping" in console.export_text()


def test_reload_hyprland_discovers_signature(tmp_path: Path, monkeypatch) -> None:
    runtime = tmp_path / "runtime"
    instance = runtime / "hypr" / "sig123"
    instance.mkdir(parents=True)

    monkeypatch.setenv("XDG_RUNTIME_DIR", str(runtime))
    monkeypatch.setenv("HYPRLAND_INSTANCE_SIGNATURE", "")
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Linux")
    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: "/usr/bin/hyprctl")

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    reload_hyprland(console)

    assert calls, "hyprctl should be invoked when signature is discovered"
    assert "-i" in calls[0]
    assert "sig123" in calls[0]
    assert "Reloaded Hyprland" in console.export_text()


def test_reload_hyprland_skips_when_unavailable(monkeypatch) -> None:
    monkeypatch.delenv("HYPRLAND_INSTANCE_SIGNATURE", raising=False)
    monkeypatch.delenv("XDG_RUNTIME_DIR", raising=False)
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Linux")
    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: "/usr/bin/hyprctl")

    console = _console()
    reload_hyprland(console)

    output = console.export_text()
    assert "signature unavailable" in output


def test_update_wallpaper_runs_swww(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    background = home / ".config" / "omarchy" / "current" / "background"
    background.parent.mkdir(parents=True)
    background.write_text("fake-image")

    monkeypatch.setenv("THEMECTL_HOME", str(home))
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Linux")
    monkeypatch.setattr("themectl.hooks.shutil.which", lambda _: "/usr/bin/swww")

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    update_wallpaper(console)

    assert calls, "swww should be invoked"
    assert str(background) in calls[0]
    assert "Updated wallpaper" in console.export_text()


def test_update_wallpaper_macos_prefers_desktoppr(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    background = home / ".config" / "omarchy" / "current" / "background"
    real = home / "wallpapers" / "catppuccin.png"
    real.parent.mkdir(parents=True)
    real.write_text("fake-image")
    background.parent.mkdir(parents=True)
    background.symlink_to(real)

    monkeypatch.setenv("THEMECTL_HOME", str(home))
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Darwin")
    monkeypatch.setattr(
        "themectl.hooks.shutil.which",
        lambda name: "/usr/local/bin/desktoppr" if name == "desktoppr" else None,
    )

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    def fail_osascript(*args, **kwargs):
        raise AssertionError("osascript should not run when desktoppr is available")

    monkeypatch.setattr("themectl.hooks._run_osascript", fail_osascript)
    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    update_wallpaper(console)

    assert calls[0][0] == "/usr/local/bin/desktoppr"
    assert str(real) in calls[0]
    assert "desktoppr" in console.export_text()


def test_update_wallpaper_macos_uses_osascript(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    background = home / ".config" / "omarchy" / "current" / "background"
    real = home / "wallpapers" / "nord.png"
    real.parent.mkdir(parents=True)
    real.write_text("fake-image")
    background.parent.mkdir(parents=True)
    background.symlink_to(real)

    monkeypatch.setenv("THEMECTL_HOME", str(home))
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Darwin")
    monkeypatch.setattr("themectl.hooks.shutil.which", lambda name: None)

    captured: dict[str, list[str]] = {}

    def fake_run(script: str, args: list[str]) -> bool:
        captured["script"] = [script]
        captured["args"] = args
        return True

    monkeypatch.setattr("themectl.hooks._run_osascript", fake_run)

    def fail_run(*args, **kwargs):
        raise AssertionError("subprocess.run should not be called")

    monkeypatch.setattr("themectl.hooks.subprocess.run", fail_run)

    console = _console()
    update_wallpaper(console)

    assert captured["args"][0] == str(real)
    assert "macOS wallpaper" in console.export_text()


def test_update_wallpaper_macos_fallback_defaults(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    background = home / ".config" / "omarchy" / "current" / "background"
    real = home / "wallpapers" / "fallback.png"
    real.parent.mkdir(parents=True)
    real.write_text("fake-image")
    background.parent.mkdir(parents=True)
    background.symlink_to(real)

    monkeypatch.setenv("THEMECTL_HOME", str(home))
    monkeypatch.setattr("themectl.hooks.platform.system", lambda: "Darwin")
    monkeypatch.setattr("themectl.hooks._run_osascript", lambda *args, **kwargs: False)

    def fake_which(name: str) -> str | None:
        if name == "defaults":
            return "/usr/bin/defaults"
        return None

    monkeypatch.setattr("themectl.hooks.shutil.which", fake_which)

    calls: list[list[str]] = []

    class Result:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return Result()

    monkeypatch.setattr("themectl.hooks.subprocess.run", fake_run)

    console = _console()
    update_wallpaper(console)

    assert calls[0][0].endswith("defaults")
    assert any(str(real) in arg for arg in calls[0])
    assert calls[1][0] == "killall"
    output = console.export_text()
    assert "wallpaper record" in output
    assert "Dock" in output


def _theme(slug: str, kind: str | None) -> Theme:
    return Theme(
        name=slug,
        slug=slug,
        display_name=slug,
        wallpapers=[],
        raw={"name": slug, "kind": kind},
        kind=kind,
    )


def test_theme_is_light_prefers_kind_then_slug() -> None:
    assert _theme("flexoki-light", "light").is_light is True
    assert _theme("tokyo-night", "dark").is_light is False
    # Legacy metadata without `kind` falls back to slug heuristics.
    assert _theme("catppuccin-latte", None).is_light is True
    assert _theme("gruvbox", None).is_light is False


def test_nvim_colorscheme_command_uses_light_flag() -> None:
    from themectl.hooks import _get_nvim_colorscheme_command

    assert "set background=light" in _get_nvim_colorscheme_command(
        "flexoki-light", True
    )
    assert "set background=dark" in _get_nvim_colorscheme_command(
        "flexoki-light", False
    )
    assert "background='light'" in _get_nvim_colorscheme_command(
        "catppuccin-latte", True
    )


def test_update_system_appearance_macos_flips_when_needed(monkeypatch) -> None:
    from themectl import hooks

    calls: list[list[str]] = []
    monkeypatch.setattr(hooks.platform, "system", lambda: "Darwin")
    monkeypatch.setattr(hooks, "_macos_is_dark", lambda: True)
    monkeypatch.setattr(
        hooks, "_run_osascript", lambda script, args: calls.append(args) or True
    )

    console = _console()
    hooks.update_system_appearance(_theme("flexoki-light", "light"), console)
    assert calls == [["light"]]
    assert "Set macOS appearance to light" in console.export_text()

    calls.clear()
    hooks.update_system_appearance(_theme("tokyo-night", "dark"), console)
    assert calls == []
    assert "already dark" in console.export_text()


def test_update_system_appearance_respects_automation_kill_switch(
    monkeypatch,
) -> None:
    from themectl import hooks

    monkeypatch.setattr(hooks.platform, "system", lambda: "Darwin")
    monkeypatch.setenv("THEME_DISABLE_EDITOR_AUTOMATION", "1")
    monkeypatch.setattr(
        hooks, "_run_osascript", lambda *_: (_ for _ in ()).throw(AssertionError())
    )
    hooks.update_system_appearance(_theme("flexoki-light", "light"), _console())


def test_reload_cmux_invokes_cli_when_running(monkeypatch, tmp_path: Path) -> None:
    from themectl import hooks

    fake_cmux = tmp_path / "cmux"
    fake_cmux.write_text("#!/bin/sh\nexit 0\n")
    fake_cmux.chmod(0o755)
    monkeypatch.setattr(hooks.platform, "system", lambda: "Darwin")
    monkeypatch.setattr(hooks, "_process_running", lambda name: name == "cmux")
    monkeypatch.setattr(hooks.shutil, "which", lambda name: str(fake_cmux))

    console = _console()
    hooks.reload_cmux(console)
    assert "Reloaded cmux" in console.export_text()


def test_reload_cmux_is_noop_off_macos(monkeypatch) -> None:
    from themectl import hooks

    monkeypatch.setattr(hooks.platform, "system", lambda: "Linux")
    monkeypatch.setattr(
        hooks, "_process_running", lambda *_: (_ for _ in ()).throw(AssertionError())
    )
    hooks.reload_cmux(_console())
