# NVIDIA Device Plugin DaemonSet
# Advertises NVIDIA GPUs as schedulable resources to Kubernetes
# Version: v0.17.0
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
  labels:
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/version: v0.17.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nvidia-device-plugin
        app.kubernetes.io/version: v0.17.0
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "true"
      hostPID: true
      priorityClassName: system-node-critical
      containers:
        - name: nvidia-device-plugin-ctr
          image: nvcr.io/nvidia/k8s-device-plugin:v0.17.0
          args:
            - "--pass-device-specs"
            - "--device-list-strategy=envvar"
            - "--device-id-strategy=uuid"
            - "--config-file=/etc/nvidia/config.yaml"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LD_LIBRARY_PATH
              value: "/usr/local/nvidia/lib64"
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: cdi-root
              mountPath: /var/run/cdi
              readOnly: true
            - name: config
              mountPath: /etc/nvidia
            - name: nvidia-driver-libs
              mountPath: /usr/local/nvidia/lib64
              readOnly: true
            - name: nix-store
              mountPath: /nix/store
              readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: cdi-root
          hostPath:
            path: /var/run/cdi
        - name: config
          configMap:
            name: nvidia-device-plugin-config
            optional: true
        - name: nvidia-driver-libs
          hostPath:
            path: /run/opengl-driver/lib
            type: Directory
        - name: nix-store
          hostPath:
            path: /nix/store
            type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-config
  namespace: kube-system
data:
  config.yaml: |
    version: v1
    flags:
      migStrategy: none
      failOnInitError: false
