from typing import Any, Callable


class Typer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def command(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

    def callback(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...


class Exit(Exception):
    def __init__(self, code: int = ...) -> None: ...


def Option(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...


def Argument(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...
